version: "3"
services:
    kubo:
        image: ipfs/kubo:latest
        ports:
            - 8090:8080
            - 5001:5001
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: defillama-answerer
